//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Configs : global::System.Configuration.ApplicationSettingsBase {
        
        private static Configs defaultInstance = ((Configs)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Configs())));
        
        public static Configs Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tiagofm.profissional@outlook.pt")]
        public string bass_email {
            get {
                return ((string)(this["bass_email"]));
            }
            set {
                this["bass_email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2X182953124818")]
        public string bass_regkey {
            get {
                return ((string)(this["bass_regkey"]));
            }
            set {
                this["bass_regkey"] = value;
            }
        }
    }
}
